trailingComma: "es5"
tabWidth: 2
semi: false
singleQuote: true
plugins:
  - prettier-plugin-astro
  - prettier-plugin-tailwindcss
overrides:
  - files:
      - "*.ts"
      - "*.tsx"
      - "*.jsx"
      - "*.js"
    options:
      tabWidth: 2
